### ISSUE TITLE
Question on Update for Existing X

### ISSUE THREAD

**Issue by Gashzilla** [codepine/testrail-api-java-client#1]
I didn't see in your example, or in the code, a very clean way to send an update for an already created run and case. I am fairly new to TestRail in general, but am hoping to integrate your client in order to update runs and cases that are established before the execution occurs.

Thanks!!!

**Comment by kunal546** [comment]
Once you get an instance of TestRail class, to update runs, you can use
```
// get run to be update
Run run = testRail.runs().get(<runId>);

// update run
run.set...

// send update to TestRail
testRail.runs().update(run).execute();
```

Similarly, you can update cases. Convention is - 
```
testRail.<entity>.<requests>.execute()
```

Hope this helps you. You can download javadoc.jar artifact from maven (link on project homepage) which has the javadoc and explore TestRail class for all the requests.
