### ISSUE TITLE
NPE in FieldDeserializer.deserialize when loading list of case fields

### ISSUE THREAD

**Issue by alexeyOnGitHub** [codepine/testrail-api-java-client#2]
using testrail-api-java-client 1.0.0 from Maven Central.

TestRail v4.1.0.3294

code:

```
    final List<CaseField> customCaseFields = client.caseFields().list().execute();
```

exception:

java.lang.NullPointerException
    at com.codepine.api.testrail.internal.FieldModule$FieldDeserializer.deserialize(FieldModule.java:65)
    at com.codepine.api.testrail.internal.FieldModule$FieldDeserializer.deserialize(FieldModule.java:51)
    at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:227)
    at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:204)
    at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:23)
    at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2993)
    at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2151)
    at com.codepine.api.testrail.Request.execute(Request.java:164)
    at org.jenkinsci.plugin.trp.TestRailClient.getCases(TestRailClient.java:156)

---

I see field.getConfigs() returns NULL in FieldModule.FieldDeserializer
field processed is:

```
Field(id=1, label=Preconditions, name=preconds, description=The preconditions of this test case. Reference other test cases with [C#] (e.g. [C17])., systemName=custom_preconds, typeId=3, type=TEXT, displayOrder=1, configs=null)
```

maybe field.getConfigs() can be modified to return an empty collection rather than Null when no configs are found?

**Comment by alexeyOnGitHub** [comment]
workaround until this is fixed: loading fields directly from REST API:


    public Collection<Case> getCases(int projectId, int suiteId) throws IOException {
        final String body = get("index.php?/api/v2/get_cases/" + projectId + "&suite_id=" + suiteId).getBody();
        final JSONArray array = new JSONArray(body);
        final Collection<Case> cases = new ArrayList<>(array.length());
        for (int i = 0; i < array.length(); i++) {
            final JSONObject json = array.getJSONObject(i);
            cases.add(createCaseFromJson(json));
        }
        return cases;
    }
    private static final String CUSTOM_FIELD_FOR_FULL_TEST_NAME = "custom_automated_test_name";

    private static Case createCaseFromJson(JSONObject json) {
        final String title = json.getString("title");
        final int id = json.getInt("id");
        final String fullTestName = json.getString(CUSTOM_FIELD_FOR_FULL_TEST_NAME);
        final Map<String, Object> fields = new HashMap<>(1);
        fields.put(CUSTOM_FIELD_FOR_FULL_TEST_NAME, fullTestName);
        return new Case().setId(id).setTitle(title).setCustomFields(fields);
    }

**Comment by kunal546** [comment]
I tested this on my end and it does not seem to be an issue even when I remove all custom fields from TestRail. TestRail server also returns an empty JSON array for the same which gets correctly deserialized.

In your case, it seems like the server response is 200 OK but the body is something else (may not even be reaching TestRail server). Did you get any other APIs working with the same TestRail configuration (end point and credentials)?

**Comment by alexeyOnGitHub** [comment]
do you have  same version of TestRail? 
our networking configuration is screwed up indeed , but I use my laptop as a "baseline": all integration tests work when I run them on my laptop - except for this request to get case fields.
maybe it's some weird custom field created in our TestRail instance that does not get those "configs" - can they be ignored if not found in response?
maybe that field is optional in our version of TestRail?..

here is the field that is loaded from the server (copied from debugger) -

    Field(id=1, label=Preconditions, name=preconds, description=The preconditions of this test case. Reference other test cases with [C#] (e.g. [C17])., systemName=custom_preconds, typeId=3, type=TEXT, displayOrder=1, configs=null)

**Comment by kunal546** [comment]
Closing since it is related to #3.
