### ISSUE TITLE
old guava causes issues

### ISSUE THREAD

**Issue by klubi** [codepine/testrail-api-java-client#21]
Hi
I have a pretty big framework, and I wanted to push results to TR, this library is awesome, but seems like version 1.0.2 uses old guava version which is in conflict to version 21.0 I already have in project.

Is there a chance for soon release of newer version with new java, since it's already in the repo?

Thanks

**Comment by welnanick** [comment]
@kunal546 please release an update. This library is currently incompatible with anything that uses guava 21.0 or higher.

**Comment by kunal546** [comment]
Sorry for the delay. v2.0.0 has been released which addresses this.
