### ISSUE TITLE
Update run will not keep old data

### ISSUE THREAD

**Issue by szabolcslevay** [codepine/testrail-api-java-client#24]
Hello,

Let's say that my Test Run **1234** contains two test cases: **111** and **222**. If I call an update to this run via `setCaseIds` to include test case **333** as well, then my run will contain only test case **333** and the old test cases will be deleted.

code:
```
List<Integer> testCaseIdToBeAdded = new ArrayList<>();
testCaseIdsToBeAdded.add(333);

Run avtiveRun = testRail.runs().get(1234).execute();
testRail.runs().update(avtiveRun.setCaseIds(testCaseIdsToBeAdded)).execute();
```

Is there a way to add test cases one by one to a run without losing the original content?

Thanks,

**Comment by kunal546** [comment]
TestRail does not support an `add/append` operation. It only supports `set/override` operation.

Currently, the only way to do that is:

`
Run activeRun = testRail.runs().get(1234).execute();
List<Integer> testCaseIds = activeRun.getCaseIds() == null ? new ArrayList<>() : new ArrayList<>(activeRun.getCaseIds());
testRail.runs.update(activeRun.setCaseIds(testCaseIds)).execute();
`

A potential enhancement for this library is to expose an `Run#addCaseIds()` operation which internally does the above.

**Comment by szabolcslevay** [comment]
Thank you, @kunal546 for your quick answer. Fixed my issue.
Keep up the good work!
