### ISSUE TITLE
How to use customfields

### ISSUE THREAD

**Issue by dengrgry** [codepine/testrail-api-java-client#30]
I'm having issues with required custom fields. Can someone point me out how to properly use them?

I add a custom field map to my test case result:
`result.setCustomFields(customParameters)`

When i check the value of the custom field in my result, it's correct.
After the test run I report my results with this code:
```
List<ResultField> customResultFields = testRailClient.resultFields().list().execute()
testRailClient.results().addForCases(run.getId(), testResults, customResultFields).execute()
```
But i'm still getting an error that custom field X is required. Without the required custom field everything is working.

**Comment by dengrgry** [comment]
@kunal546 can you maybe help me?

**Comment by davidbrazilparker** [comment]
Example of setting custom case fields and updating a `case`.

```
List<CaseField> caseFields = testRailInstance.caseFields().list().execute();
Case caseObject = testRailInstance.cases().get(someCaseID, caseFields).execute();

Map<String,Object> customFields = new HashMap<>();
customFields.put("fieldKey","fieldValue");

testRailInstance.cases().update(caseObject,caseFields).execute();
```

**Comment by kunal546** [comment]
Thanks @davidbrazilparker !
@dengrgry are you still having an issue?

**Comment by kunal546** [comment]
Closing this. Please re-open if you still need help.

**Comment by Dietmar1963** [comment]
Hi @kunal546 

I am trying to  update a test case

Case(id=2, title=Add numbered list to inline table within an document, sectionId=1, typeId=11, priorityId=2, milestoneId=null, refs=null, createdBy=1, createdOn=Tue Apr 26 17:01:17 CEST 2022, updatedBy=1, updatedOn=Tue Apr 26 21:05:18 CEST 2022, estimate=8m, estimateForecast=7m 36s, suiteId=1, customFields={mission=test, automation_type=null, tc_automated=null, preconds=null, expected=null, steps_separated=null, steps=null, goals=null})

**Comment by Dietmar1963** [comment]
Hi @kunal546

I am trying to update a test case, but it does not work. I am using the cloud based evaluation instance of testrail.

`public class tr {

    public static void main(String[] args) {
        final String USERNAME = "xxx@live.com";
        final String PWD = "xxx";
        final String URL = "https://xxx.testrail.io/";
        final Integer testCaseId = 2;
        
        // create a TestRail instance
        TestRail testRail = TestRail.builder(URL, USERNAME, PWD).build();

        // Get test Case 2
        List<CaseField> caseFields = testRail.caseFields().list().execute();
        Case caseObject = testRail.cases().get(testCaseId, caseFields).execute();
                
       //put
        Map<String,Object> customFields = new HashMap<>();
        customFields.put("custom_automation_type",1);
        customFields.put("custom_tc_automated",2);
        
        testRail.cases().update(caseObject,caseFields).execute();
            }
}`

![image](https://user-images.githubusercontent.com/56964291/165377472-e73fe7ff-eb9d-40ea-b130-7837bf41be54.png)


But the caseFields are not updated. Any idea why not?

Thank you  -Best -Dietmar
