### ISSUE TITLE
i cannot find results()

### ISSUE THREAD

**Issue by dularijb** [codepine/testrail-api-java-client#32]
while trying to add results, i get an error saying it cannot resolve symbol results()

 // add test result
    List<ResultField> customResultFields = testRail.resultFields().list().execute();
    testRail.results().addForCase(run.getId(), testCase.getId(), new Result().setStatusId(1), customResultFields).execute();

can you please post the complete example?

**Comment by kunal546** [comment]
Sounds like you are having a compilation error. For an instance of class `com.codepine.api.testrail.TestRail`, you should be able to resolve `results()`.

Ref: https://github.com/codepine/testrail-api-java-client/blob/master/src/main/java/com/codepine/api/testrail/TestRail.java#L225

If this is still an issue for you, please re-open this issue with a complete stack trace.
