### ISSUE TITLE
Ongoing Development in new Fork

### ISSUE THREAD

**Issue by davidbrazilparker** [codepine/testrail-api-java-client#34]
Hello everyone! As far as I can tell the original author of this repo is no longer actively maintaining/developing this software. I've created a new forked version with updates to support features available in TestRail API version 5.3:

https://github.com/chapeco/testrail-api-java-client

Going forward, I am planning on supporting the issues that are still open in this repo. I will just need to move them over to the new repo and deal with them from there.

**Comment by davidbrazilparker** [comment]
New dependency can be found here:

https://search.maven.org/artifact/io.github.chapeco.api.testrail/testrail-api-java-client/2.0.2/jar

**Comment by kunal546** [comment]
Hi! While I agree that I have been unable to dedicate time for this project, I don’t think creating a separate copy is the right solution. I don’t think it is a good customer experience and expect people to keep changing dependencies (is there a guarantee that the new repo will be supported forever).

The idea behind an open source project was to have everyone contribute via pull requests. I suggest you contribute via pull requests. I can review and merge. I have also added owners to this project in the past who have more permissions like merge.

Currently, only I can perform maven release though. I have not figured out a good way to have owners do it. I could also make you the owner of this project so you can also merge other pull requests. But again, I highly recommend that you start with pull requests contributing to this repository.

Thanks!
