### ISSUE TITLE
impossible to get response size

### ISSUE THREAD

**Issue by Dyadko** [codepine/testrail-api-java-client#37]
calling for a plan, a run, a milestone, etc... limit of results is 250. since the whole results list size is unavailable, it's unable to know how many offsets (`testRail.plans().list(5).offset(250).execute()`) needed to enumerate all the results.

**Comment by kunal546** [comment]
I am unable to understand your question completely. The TestRail API provides two request parameters related to pagination - `limit` and `offset`. Ref: http://docs.gurock.com/testrail-api2/reference-plans#get_plans

The idea is to get a single page of results and keep iterating until you get to results which are less than the `limit` or to be safe until you hit an empty page. Here's one way to consume all plans:

```java
List<Plan> plans;
int offset = 0;
int limit = 1;
do {
    // query for a page of plans
    plans = testRail.plans().list(1).limit(limit).offset(offset).execute();

    // use current page of plans before processing next page
    System.out.println(plans);

    // move offset to the end of the page
    offset += plans.size();
} while (!plans.isEmpty());
```

Please re-open this if you still think this is an issue with this library.
