### ISSUE TITLE
when server gives 301 response, should process the new URL correctly

### ISSUE THREAD

**Issue by alexeyOnGitHub** [codepine/testrail-api-java-client#6]
I guess our server is configured in a bit weird way... but it returns 301 for TestRail URLs and then still works.
the library, though, only accepts 200 (OK) and considers 301 to be an error (which is actually a valid situation).

I wonder if you could process 301 "moved permanently" response in the lib...

com.codepine.api.testrail.TestRailException: 301 - server did not send any error message
 at com.codepine.api.testrail.TestRailException$Builder.build(TestRailException.java:57)
 at com.codepine.api.testrail.Request.execute(Request.java:138)
 at org.jenkinsci.plugin.trp.TestRailClient.getSuiteId(TestRailClient.java:114)

**Comment by kunal546** [comment]
It should follow the redirects (for GET) automatically. I think it won't if the redirect is from HTTP to HTTPS or vice-versa. Is that the case?

**Comment by alexeyOnGitHub** [comment]
I'm working with our IT to figure out how redirect works in that environment..
maybe it is a problem with the server configuration. but still - I see this check for one specific code 200 in Request class:

            if (responseCode != HttpURLConnection.HTTP_OK) {

**Comment by kunal546** [comment]
Java HttpUrlConnection follows redirects by default so the redirects are taken care of before it reaches that statement.

**Comment by kunal546** [comment]
You can set the endPoint in the TestRail.Builder to the location where it's "moved permanently". There is also an option to override the default apiPath in TestRail.Builder which by default is "index.php?/api/v2/".

**Comment by alexeyOnGitHub** [comment]
alright, let's close this as "user error". I think the problem is that the network configuration in that environment where I tried running this app was screwed up -  it did several redirects, possibly to HTTPS and then back.
