### ISSUE TITLE
configIds and caseIds of plan.entry

### ISSUE THREAD

**Issue by paxcow** [codepine/testrail-api-java-client#9]
configIds and caseIds are beings et for a plan.entry. however when adding that entry to a plan, the configs and selected cases are not added.

**Comment by kunal546** [comment]
You need to explicitly setIncludeAll(false) for Plan.Entry. This is the behavior by TestRail API.

**Comment by paxcow** [comment]
kunal, cannot set caseIDs aswell, should i be setting it for an entry or a run within the entry ? (both not working tho )

**Comment by kunal546** [comment]
Setting include_all to false (via Plan.Entry#setIncludeAll) and setting case_ids (via Plan.Entry#setCaseIds) works for me. Can you please paste your code and what is your intent?

From the documentation at http://docs.gurock.com/testrail-api2/reference-plans#add_plan_entry (see example) -
```
This will effectively create a new test run for each array element of the runs field. The top-level
assignedto_id, include_all and case_ids fields specify the default assignee and test case selection
for all test runs. You can override these fields for each test run as demonstrated in the example above.
```

**Comment by paxcow** [comment]
What I'm trying to do is, add certain test cases and configs to an existing test plan, so heres my code:

        Plan.Entry newEntry = new Plan.Entry();
        Plan.Entry.Run tempRun = new Plan.Entry.Run();
         List setRuns = new ArrayList<>();

// I add a couple of runs with the following attributes in a for loop here
                tempRun.setConfigIds(thisRun.getConfigIds());
                tempRun.setConfig(thisRun.getConfig());
                tempRun.setName(thisRun.getName());
                tempRun.setDescription(thisRun.getDescription());
                tempRun.setCreatedBy(thisRun.getCreatedBy());
                tempRun.setIncludeAll(false);
                tempRun.setCompleted(false);
                tempRun.setEntryIndex(thisRun.getEntryIndex());
                tempRun.setSuiteId(thisRun.getSuiteId());
                tempRun.setProjectId(thisRun.getProjectId());
                tempRun.setPlanId(thisRun.getPlanId());
                tempRun.setConfig(thisRun.getConfig());
                tempRun.setEntryId(thisRun.getEntryId());
                tempRun.setCreatedOn(thisRun.getCreatedOn());
                tempRun.setAssignedtoId(thisRun.getAssignedtoId());
               setRuns.add(tempRun);


newEntry.setRuns(setRuns);
newEntry.setSuiteId(newEntry.getSuiteId());
newEntry.setIncludeAll(false);
newEntry.setCaseIds(caseIds);


The problem here is, I got to add the test cases after I added setIncludeAll(false); however, even though I send the configIDs and Config strings,  the entry does not get configs added.

Thank you for your swift reply.

**Comment by gauravpatel2016** [comment]
I have similar issue.

Here is my code:

 // Create a Test Run Entry
    Plan.Entry newEntry = new Plan.Entry();
    Plan.Entry.Run tempRun = new Plan.Entry.Run();
    List setRuns = new ArrayList<>();

    // Set parameters of entry
    tempRun.setName("Check").setProjectId(34).setPlanId(45237).setSuiteId(10685).setIncludeAll(false).setCaseIds(myList);
    setRuns.add(tempRun);
    newEntry.setRuns(setRuns).setSuiteId(10685).setIncludeAll(false).setCaseIds(myList);


    // Add it to test plan
    testRail.plans().addEntry(45237, newEntry).execute();
